import { StyleSheet } from 'react-native';
import { spacing, borderRadius, fontSize, fontWeight, fontFamily, shadows } from '../constants/theme';

export const createStyles = (colors) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        header: {
            paddingTop: 60,
            paddingBottom: spacing.xl,
            paddingHorizontal: spacing.xl,
            borderBottomLeftRadius: borderRadius.xxl,
            borderBottomRightRadius: borderRadius.xxl,
        },
        headerTitle: {
            fontSize: fontSize.xxxl,
            fontFamily: fontFamily.bold,
            color: colors.textWhite,
        },
        headerTopRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        headerActionButton: {
            width: 34,
            height: 34,
            borderRadius: 17,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.3)',
            alignItems: 'center',
            justifyContent: 'center',
        },
        content: {
            flex: 1,
            paddingTop: spacing.xl,
        },
        centerContainer: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: colors.background,
            gap: spacing.md,
        },
        loadingText: {
            fontSize: fontSize.lg,
            fontFamily: fontFamily.medium,
            color: colors.textLight,
        },
        emptyState: {
            alignItems: 'center',
            paddingVertical: spacing.xxxl * 2,
        },
        emptyText: {
            fontSize: fontSize.xl,
            fontFamily: fontFamily.bold,
            color: colors.text,
            marginBottom: spacing.sm,
            marginTop: spacing.lg,
        },
        emptySubtext: {
            fontSize: fontSize.sm,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
            textAlign: 'center',
        },
        summaryCard: {
            backgroundColor: colors.surface,
            marginHorizontal: spacing.xl,
            marginBottom: spacing.lg,
            padding: spacing.lg,
            borderRadius: borderRadius.lg,
            ...shadows.small,
        },
        summaryTitle: {
            fontSize: fontSize.base,
            fontFamily: fontFamily.semibold,
            color: colors.text,
            marginBottom: spacing.md,
        },
        summaryRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        summaryItem: {
            flex: 1,
            alignItems: 'center',
        },
        summaryLabel: {
            fontSize: fontSize.xs,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
            marginBottom: spacing.xs,
        },
        summaryValue: {
            fontSize: fontSize.base,
            fontFamily: fontFamily.bold,
            color: colors.text,
        },
        summaryValueNegative: {
            color: colors.error,
        },
        summaryDivider: {
            width: 1,
            height: 28,
            backgroundColor: colors.border,
        },
        budgetCard: {
            backgroundColor: colors.surface,
            marginHorizontal: spacing.xl,
            marginBottom: spacing.lg,
            padding: spacing.lg,
            borderRadius: borderRadius.lg,
            ...shadows.medium,
        },
        budgetCardCritical: {
            borderWidth: 1,
            borderColor: colors.error,
            backgroundColor: (colors.error) + '0F',
        },
        budgetCardWarning: {
            borderWidth: 1,
            borderColor: colors.warning,
            backgroundColor: (colors.warning) + '10',
        },
        budgetHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: spacing.md,
        },
        budgetLeft: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        budgetCategory: {
            fontSize: fontSize.lg,
            fontFamily: fontFamily.bold,
            color: colors.text,
            marginLeft: spacing.sm,
        },
        budgetRight: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: spacing.sm,
        },
        budgetLimit: {
            fontSize: fontSize.xl,
            fontFamily: fontFamily.bold,
            color: colors.primary,
        },
        budgetPercentageBadge: {
            paddingHorizontal: spacing.sm,
            paddingVertical: spacing.xs,
            borderRadius: borderRadius.md,
        },
        budgetPercentageText: {
            fontSize: fontSize.lg,
            fontFamily: fontFamily.bold,
        },
        progressBarBg: {
            height: 12,
            backgroundColor: colors.border,
            borderRadius: borderRadius.full,
            overflow: 'hidden',
            marginBottom: spacing.md,
        },
        progressBar: {
            height: '100%',
            borderRadius: borderRadius.full,
        },
        budgetInfo: {
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
        budgetSpent: {
            fontSize: fontSize.sm,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
        },
        budgetRemaining: {
            fontSize: fontSize.sm,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
        },
        budgetAlert: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            gap: spacing.sm,
            borderRadius: borderRadius.md,
            padding: spacing.md,
            marginTop: spacing.md,
        },
        budgetAlertText: {
            flex: 1,
        },
        budgetAlertTitle: {
            fontSize: fontSize.sm,
            fontFamily: fontFamily.semibold,
            color: colors.error,
            marginBottom: 2,
        },
        budgetAlertSubtitle: {
            fontSize: fontSize.xs,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
        },
        addButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: colors.surface,
            marginHorizontal: spacing.xl,
            padding: spacing.lg,
            borderRadius: borderRadius.lg,
            borderWidth: 2,
            borderStyle: 'dashed',
            borderColor: colors.primary,
        },
        addButtonText: {
            fontSize: fontSize.base,
            fontFamily: fontFamily.semibold,
            color: colors.primary,
            marginLeft: spacing.sm,
        },
        modalOverlay: {
            flex: 1,
            backgroundColor: colors.overlay,
            justifyContent: 'flex-end',
        },
        overlayTouchArea: {
            flex: 1,
        },
        handleBar: {
            width: 40,
            height: 4,
            backgroundColor: colors.border,
            borderRadius: 2,
            alignSelf: 'center',
            marginTop: spacing.md,
            marginBottom: spacing.xs,
        },
        modal: {
            backgroundColor: colors.surface,
            borderTopLeftRadius: borderRadius.xxxl,
            borderTopRightRadius: borderRadius.xxxl,
            maxHeight: '80%',
        },
        modalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: spacing.xl,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        modalTitle: {
            fontSize: fontSize.xxl,
            fontFamily: fontFamily.bold,
            color: colors.text,
        },
        closeButton: {
            fontSize: fontSize.huge,
            color: colors.textLight,
            fontWeight: fontWeight.light,
        },
        modalContent: {
            padding: spacing.xl,
        },
        label: {
            fontSize: fontSize.base,
            fontFamily: fontFamily.semibold,
            color: colors.text,
            marginBottom: spacing.sm,
            marginTop: spacing.lg,
        },
        categoriesRow: {
            flexDirection: 'row',
            gap: spacing.sm,
        },
        categoryOption: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: spacing.sm,
            paddingHorizontal: spacing.md,
            borderRadius: borderRadius.lg,
            borderWidth: 1,
            borderColor: colors.border,
            backgroundColor: colors.background,
        },
        categoryOptionActive: {
            backgroundColor: colors.primary,
            borderColor: colors.primary,
        },
        categoryOptionText: {
            fontSize: fontSize.sm,
            fontFamily: fontFamily.regular,
            color: colors.text,
            marginLeft: spacing.xs,
        },
        amountContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: colors.background,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: borderRadius.md,
            paddingLeft: spacing.lg,
        },
        currencySymbol: {
            fontSize: fontSize.xl,
            fontFamily: fontFamily.semibold,
            color: colors.primary,
            marginRight: spacing.sm,
        },
        amountInput: {
            flex: 1,
            padding: spacing.lg,
            fontSize: fontSize.xl,
            fontFamily: fontFamily.semibold,
            color: colors.text,
        },
        saveButton: {
            backgroundColor: colors.primary,
            padding: spacing.lg,
            borderRadius: borderRadius.lg,
            alignItems: 'center',
            marginTop: spacing.xl,
            ...shadows.colored,
        },
        saveButtonContent: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        saveButtonText: {
            color: colors.textWhite,
            fontSize: fontSize.lg,
            fontFamily: fontFamily.bold,
        },
        deleteButton: {
            marginTop: spacing.md,
            padding: spacing.lg,
            borderRadius: borderRadius.lg,
            alignItems: 'center',
            borderWidth: 1,
            borderColor: colors.error,
            backgroundColor: `${colors.error}14`,
        },
        deleteButtonContent: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        deleteButtonText: {
            color: colors.error,
            fontSize: fontSize.base,
            fontFamily: fontFamily.semibold,
        },
        advisorSection: {
            marginHorizontal: spacing.xl,
            marginBottom: spacing.lg,
            backgroundColor: colors.surface,
            borderRadius: borderRadius.lg,
            padding: spacing.lg,
            borderWidth: 1,
            borderColor: colors.primary + '25',
        },
        advisorHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: spacing.sm,
            marginBottom: spacing.xs,
        },
        advisorTitle: {
            fontSize: fontSize.base,
            fontFamily: fontFamily.semibold,
            color: colors.text,
        },
        advisorHint: {
            fontSize: fontSize.xs,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
            marginBottom: spacing.md,
        },
        advisorButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: spacing.sm,
            backgroundColor: colors.primary,
            borderRadius: borderRadius.full,
            paddingVertical: spacing.sm,
            paddingHorizontal: spacing.lg,
        },
        advisorButtonDisabled: { opacity: 0.6 },
        advisorButtonText: {
            color: colors.textWhite,
            fontSize: fontSize.sm,
            fontFamily: fontFamily.semibold,
        },
        adviceCard: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginTop: spacing.md,
            backgroundColor: colors.background,
            borderRadius: borderRadius.md,
            padding: spacing.md,
            borderWidth: 1,
            borderColor: colors.border,
        },
        adviceLeft: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            gap: spacing.sm,
            flex: 1,
        },
        adviceInfo: { flex: 1 },
        adviceCategory: {
            fontSize: fontSize.sm,
            fontFamily: fontFamily.semibold,
            color: colors.text,
        },
        adviceReason: {
            fontSize: fontSize.xs,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
            marginTop: 2,
        },
        adviceMeta: {
            fontSize: fontSize.xs,
            fontFamily: fontFamily.medium,
            color: colors.primary,
            marginTop: spacing.xs,
        },
        applyButton: {
            backgroundColor: colors.primary,
            borderRadius: borderRadius.md,
            paddingHorizontal: spacing.md,
            paddingVertical: spacing.xs,
            marginLeft: spacing.sm,
        },
        applyButtonText: {
            color: colors.textWhite,
            fontSize: fontSize.xs,
            fontFamily: fontFamily.semibold,
        },
        noAdviceText: {
            fontSize: fontSize.xs,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
            textAlign: 'center',
            marginTop: spacing.md,
        },
    });
