import { StyleSheet } from 'react-native';
import { spacing, borderRadius, fontSize, fontWeight, fontFamily, shadows, sizes } from '../constants/theme';

export const createStyles = (colors) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    centerContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background,
        gap: spacing.md,
    },
    header: {
        paddingTop: sizes.headerHeight,
        paddingBottom: spacing.xl,
        paddingHorizontal: spacing.xl,
        borderBottomLeftRadius: borderRadius.xxl,
        borderBottomRightRadius: borderRadius.xxl,
    },
    headerTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: fontSize.xxxl,
        fontFamily: fontFamily.bold,
        color: colors.textWhite,
    },
    headerActionButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    content: {
        flex: 1,
    },
    loadingText: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
    },
    deletingToast: {
        position: 'absolute',
        bottom: spacing.xxl + sizes.fabSize + spacing.sm,
        alignSelf: 'center',
        backgroundColor: colors.surface,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.lg,
        borderRadius: borderRadius.full,
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
        ...shadows.small,
    },
    deletingText: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.medium,
        color: colors.text,
    },
    emptyState: {
        alignItems: 'center',
        marginTop: 80,
        paddingHorizontal: spacing.xl,
    },
    emptyText: {
        fontSize: fontSize.xl + 2,
        fontFamily: fontFamily.semibold,
        color: colors.text,
        marginBottom: spacing.sm,
        marginTop: spacing.lg,
    },
    emptySubtext: {
        fontSize: fontSize.md,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
        textAlign: 'center',
    },
    chartSection: {
        paddingBottom: 100,
    },
    chartContainer: {
        backgroundColor: colors.surface,
        margin: spacing.xl,
        marginBottom: spacing.md,
        padding: spacing.xl,
        borderRadius: borderRadius.xl,
        ...shadows.medium,
        alignItems: 'center',
    },
    chartTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        marginBottom: spacing.lg,
    },
    chartTitle: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    pieWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing.md,
    },
    donutCenter: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    donutTotal: {
        fontSize: fontSize.xl,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    donutLabel: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginTop: 2,
    },
    legendsDivider: {
        height: 1,
        backgroundColor: colors.border,
        marginTop: spacing.lg,
        marginBottom: spacing.md,
    },
    legendsInline: {
        width: '100%',
    },
    legendsTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing.lg,
    },
    legendsTitle: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: colors.overlay,
        justifyContent: 'flex-end',
    },
    overlayTouchArea: {
        flex: 1,
    },
    handleBar: {
        width: 40,
        height: 4,
        backgroundColor: colors.border,
        borderRadius: 2,
        alignSelf: 'center',
        marginTop: spacing.md,
        marginBottom: spacing.xs,
    },
    categoryModal: {
        backgroundColor: colors.surface,
        borderTopLeftRadius: borderRadius.xxxl,
        borderTopRightRadius: borderRadius.xxxl,
        maxHeight: '80%',
        paddingBottom: spacing.xl,
    },
    categoryModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: spacing.xl,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    categoryModalTitle: {
        fontSize: fontSize.xxxl,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    closeButton: {
        fontSize: fontSize.huge,
        color: colors.textLight,
        fontWeight: fontWeight.light,
    },
    emptyCategory: {
        padding: 40,
        alignItems: 'center',
    },
    emptyCategoryText: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
    },
    swipeRow: {
        backgroundColor: colors.surface,
    },
    categoryDayHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.xl,
        paddingTop: spacing.lg,
        paddingBottom: spacing.sm,
        backgroundColor: colors.surface,
    },
    categoryDayTitle: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    categoryDaySubtitle: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
        marginTop: 2,
    },
    categoryDayTotal: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    categoryListContent: {
        paddingBottom: spacing.lg,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        marginHorizontal: spacing.xl,
        marginTop: spacing.lg,
        marginBottom: spacing.md,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.md,
        borderRadius: borderRadius.lg,
        ...shadows.medium,
    },
    stickySummary: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.surface,
        marginHorizontal: spacing.xl,
        marginBottom: spacing.md,
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.lg,
        borderRadius: borderRadius.lg,
        ...shadows.small,
    },
    stickySummaryItem: {
        flex: 1,
        alignItems: 'flex-start',
    },
    stickyLabel: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.semibold,
        color: colors.textLight,
        marginBottom: spacing.xs,
    },
    stickyAmount: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    stickyDivider: {
        width: 1,
        height: 36,
        backgroundColor: colors.border,
        marginHorizontal: spacing.md,
    },
    summaryCard: {
        backgroundColor: colors.surface,
        marginHorizontal: spacing.xl,
        marginBottom: spacing.md,
        padding: spacing.lg,
        borderRadius: borderRadius.xl,
        ...shadows.small,
    },
    summaryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: spacing.md,
    },
    summaryTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    summaryTitle: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    summaryGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
    },
    summaryTile: {
        flexGrow: 1,
        flexBasis: '30%',
        minWidth: 120,
        padding: spacing.md,
        borderRadius: borderRadius.lg,
    },
    summaryTileIcon: {
        width: 30,
        height: 30,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing.sm,
    },
    summaryTileLabel: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.semibold,
        color: colors.textLight,
        marginBottom: spacing.xs,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
    },
    summaryTileValue: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    summaryBudgetRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginTop: spacing.md,
        paddingTop: spacing.sm,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        gap: spacing.xs,
    },
    summaryBudgetLabel: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
        marginRight: spacing.xs,
    },
    summaryBudgetValue: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    summaryBudgetValueNegative: {
        color: colors.error,
    },
    summaryBudgetDivider: {
        fontSize: fontSize.xs,
        color: colors.textLight,
        marginHorizontal: spacing.xs,
    },
        summaryBudgetValueMuted: {
            fontSize: fontSize.sm,
            fontFamily: fontFamily.semibold,
            color: colors.textLight,
        },
        summaryTotalsText: {
            marginTop: spacing.sm,
            fontSize: fontSize.xs,
            fontFamily: fontFamily.regular,
            color: colors.textLight,
        },
    summaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: spacing.xs,
    },
    summaryLabel: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
    },
    summaryValue: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    summaryPlaceholder: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.semibold,
        color: colors.textLight,
    },
    summaryMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: spacing.sm,
        paddingTop: spacing.sm,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    summaryMetaLabel: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
    },
    summaryMetaValue: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    filterSummaryCard: {
        backgroundColor: colors.surface,
        marginHorizontal: spacing.xl,
        marginBottom: spacing.md,
        padding: spacing.lg,
        borderRadius: borderRadius.xl,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        ...shadows.small,
    },
    filterSummaryLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
    },
    filterSummaryIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterSummaryTitle: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    filterSummarySubtitle: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
        marginTop: 2,
    },
    filterSummaryRight: {
        alignItems: 'flex-end',
    },
    filterSummaryTotal: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    filterSummaryCount: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
        marginTop: spacing.xs,
    },
    incomeSection: {
        backgroundColor: colors.surface,
        marginHorizontal: spacing.xl,
        marginBottom: spacing.md,
        padding: spacing.lg,
        borderRadius: borderRadius.xl,
        ...shadows.small,
    },
    incomeHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: spacing.md,
    },
    incomeFilters: {
        marginBottom: spacing.md,
        gap: spacing.sm,
    },
    incomePeriodRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
    },
    incomePeriodChip: {
        paddingVertical: spacing.xs,
        paddingHorizontal: spacing.md,
        borderRadius: borderRadius.full,
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
    },
    incomePeriodChipActive: {
        backgroundColor: colors.success,
        borderColor: colors.success,
    },
    incomePeriodText: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.semibold,
        color: colors.textLight,
    },
    incomePeriodTextActive: {
        color: colors.textWhite,
    },
    incomeSearch: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: borderRadius.lg,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderWidth: 1,
        borderColor: colors.border,
    },
    incomeSearchInput: {
        flex: 1,
        fontSize: fontSize.sm,
        fontFamily: fontFamily.regular,
        color: colors.text,
    },
    incomeClearButton: {
        marginLeft: spacing.xs,
    },
    incomeCategoryRow: {
        flexDirection: 'row',
        gap: spacing.sm,
        paddingVertical: spacing.xs,
    },
    incomeCategoryChip: {
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
        paddingVertical: spacing.xs,
        paddingHorizontal: spacing.md,
        borderRadius: borderRadius.full,
    },
    incomeCategoryChipActive: {
        backgroundColor: colors.success,
        borderColor: colors.success,
    },
    incomeCategoryText: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.semibold,
        color: colors.textLight,
    },
    incomeCategoryTextActive: {
        color: colors.textWhite,
    },
    incomeTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    incomeTitle: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    incomeSubtitle: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
        marginTop: 2,
    },
    incomeTotal: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.success,
    },
    incomeList: {
        marginTop: spacing.xs,
    },
    incomeEmpty: {
        paddingVertical: spacing.md,
        alignItems: 'center',
    },
    incomeEmptyText: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
    },
    incomeToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: spacing.sm,
    },
    incomeToggleText: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
        color: colors.textLight,
    },
    periodFiltersRow: {
        flexDirection: 'row',
        gap: spacing.sm,
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.xs,
    },
    periodFilterChip: {
        paddingVertical: spacing.xs,
        paddingHorizontal: spacing.md,
        borderRadius: borderRadius.full,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        minHeight: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    periodFilterChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    periodFilterText: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    periodFilterTextActive: {
        color: colors.textWhite,
    },
    categoryQuickRow: {
        flexDirection: 'row',
        gap: spacing.sm,
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.md,
    },
    categoryQuickChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.xs,
        paddingVertical: spacing.xs,
        paddingHorizontal: spacing.md,
        borderRadius: borderRadius.full,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
    },
    categoryDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    categoryQuickText: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.semibold,
        color: colors.text,
        maxWidth: 120,
    },
    quickFiltersRow: {
        flexDirection: 'row',
        gap: spacing.sm,
        paddingHorizontal: spacing.xl,
        paddingTop: spacing.md,
        paddingBottom: spacing.md,
    },
    quickFilterChip: {
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.lg,
        borderRadius: borderRadius.full,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
    },
    quickFilterChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    quickFilterText: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    quickFilterTextActive: {
        color: colors.textWhite,
    },
    quickAddSection: {
        marginHorizontal: spacing.xl,
        marginBottom: spacing.md,
        padding: spacing.lg,
        borderRadius: borderRadius.xl,
        backgroundColor: colors.surface,
        ...shadows.small,
    },
    quickAddHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    quickAddHeaderText: {
        flex: 1,
    },
    quickAddTitle: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    quickAddHint: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
        marginTop: 2,
    },
    quickAddRow: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    quickAddChip: {
        backgroundColor: colors.background,
        borderRadius: borderRadius.lg,
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.lg,
        minWidth: 140,
        borderWidth: 1,
        borderColor: colors.border,
    },
    quickAddChipTitle: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
        color: colors.text,
        marginBottom: spacing.xs,
    },
    quickAddChipAmount: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.bold,
        color: colors.primary,
    },
    searchInput: {
        flex: 1,
        fontSize: fontSize.base,
        fontFamily: fontFamily.regular,
        color: colors.text,
        padding: 0,
    },
    clearButton: {
        padding: spacing.xs,
        marginLeft: spacing.sm,
    },
    sortContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.xl,
        paddingVertical: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    sortLabel: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
    },
    sortButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.md,
        borderRadius: borderRadius.md,
        borderWidth: 1,
        borderColor: colors.border,
    },
    sortButtonText: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    sortDropdown: {
        position: 'absolute',
        top: 50,
        right: spacing.xl,
        backgroundColor: colors.surface,
        borderRadius: borderRadius.md,
        borderWidth: 1,
        borderColor: colors.border,
        ...shadows.large,
        zIndex: 1000,
        minWidth: 150,
    },
    sortOption: {
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: colors.borderLight,
    },
    sortOptionActive: {
        backgroundColor: colors.primaryBg,
    },
    sortOptionText: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.medium,
        color: colors.text,
    },
    sortOptionTextActive: {
        color: colors.primary,
        fontFamily: fontFamily.bold,
    },
    statsContainer: {
        backgroundColor: colors.surface,
        margin: spacing.xl,
        marginBottom: spacing.md,
        padding: spacing.lg,
        borderRadius: borderRadius.xl,
        ...shadows.small,
    },
    statsTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.lg,
    },
    statsTitle: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    statsRow: {
        flexDirection: 'row',
        gap: spacing.md,
        marginBottom: spacing.md,
    },
    statCompact: {
        flex: 1,
        backgroundColor: colors.background,
        padding: spacing.lg,
        borderRadius: borderRadius.md,
        alignItems: 'flex-start',
    },
    statIconCircle: {
        width: 32,
        height: 32,
        borderRadius: borderRadius.full,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: spacing.sm,
    },
    statLabel: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.medium,
        color: colors.textLight,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: spacing.xs,
    },
    statValue: {
        fontSize: fontSize.lg,
        fontFamily: fontFamily.bold,
        color: colors.text,
        marginBottom: 2,
    },
    statSubtext: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
    },
    statTopCategory: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        padding: spacing.lg,
        borderRadius: borderRadius.md,
    },
    statTopCategoryInfo: {
        flex: 1,
        marginLeft: spacing.md,
    },
    statTopCategoryName: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.bold,
        color: colors.text,
    },
    statTopCategoryBadge: {
        backgroundColor: colors.successBg,
        paddingVertical: spacing.xs,
        paddingHorizontal: spacing.md,
        borderRadius: borderRadius.full,
    },
    statTopCategoryBadgeText: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.bold,
        color: colors.success,
    },
});
