import { StyleSheet } from 'react-native';
import { spacing, borderRadius, fontSize, fontWeight, fontFamily, shadows } from '../constants/theme';

export const createStyles = (colors) => StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    centerContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background,
        gap: spacing.md,
    },
    header: {
        paddingTop: 60,
        paddingBottom: spacing.xl,
        paddingHorizontal: spacing.xl,
        borderBottomLeftRadius: borderRadius.xxl,
        borderBottomRightRadius: borderRadius.xxl,
    },
    headerTitle: { fontSize: fontSize.xxxl, fontFamily: fontFamily.bold, color: colors.textWhite },
    loadingText: { fontSize: fontSize.lg, fontFamily: fontFamily.medium, color: colors.textLight },
    headerStats: { marginTop: spacing.md },
    headerLabel: { fontSize: fontSize.sm, fontFamily: fontFamily.medium, color: 'rgba(255,255,255,0.7)' },
    headerAmount: { fontSize: fontSize.xxl, fontFamily: fontFamily.bold, color: colors.textWhite },
    content: { flex: 1, paddingTop: spacing.lg },
    emptyState: { alignItems: 'center', paddingVertical: spacing.xxxl * 2 },
    emptyText: { fontSize: fontSize.xl, fontFamily: fontFamily.bold, color: colors.text, marginBottom: spacing.sm, marginTop: spacing.lg },
    emptySubtext: { fontSize: fontSize.sm, fontFamily: fontFamily.regular, color: colors.textLight, textAlign: 'center' },
    card: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.surface,
        marginHorizontal: spacing.xl,
        marginBottom: spacing.md,
        padding: spacing.lg,
        borderRadius: borderRadius.lg,
        ...shadows.medium,
    },
    cardInactive: { opacity: 0.5 },
    cardLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    iconContainer: {
        width: 44,
        height: 44,
        borderRadius: borderRadius.full,
        backgroundColor: colors.primaryBg,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: spacing.md,
    },
    iconInactive: { backgroundColor: colors.border },
    cardInfo: { flex: 1, marginRight: spacing.sm },
    cardTitle: { fontSize: fontSize.base, fontFamily: fontFamily.semibold, color: colors.text, marginBottom: 2 },
    textInactive: { color: colors.textLight },
    cardSubtext: { fontSize: fontSize.xs, fontFamily: fontFamily.regular, color: colors.textLight },
    cardRight: { alignItems: 'flex-end' },
    cardAmount: { fontSize: fontSize.lg, fontFamily: fontFamily.bold, color: colors.primary, marginBottom: spacing.xs },
    switch: { transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }] },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.surface,
        marginHorizontal: spacing.xl,
        padding: spacing.lg,
        borderRadius: borderRadius.lg,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: colors.primary,
        marginTop: spacing.sm,
    },
    addButtonText: { fontSize: fontSize.base, fontFamily: fontFamily.semibold, color: colors.primary },
    modalOverlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
    overlayTouchArea: { flex: 1 },
    handleBar: { width: 40, height: 4, backgroundColor: colors.border, borderRadius: 2, alignSelf: 'center', marginTop: spacing.md, marginBottom: spacing.xs },
    modal: { backgroundColor: colors.surface, borderTopLeftRadius: borderRadius.xxxl, borderTopRightRadius: borderRadius.xxxl, maxHeight: '85%' },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: spacing.xl,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    modalTitle: { fontSize: fontSize.xxl, fontFamily: fontFamily.bold, color: colors.text },
    closeButton: { fontSize: fontSize.huge, color: colors.textLight, fontWeight: fontWeight.light },
    modalContent: { padding: spacing.xl },
    label: { fontSize: fontSize.base, fontFamily: fontFamily.semibold, color: colors.text, marginBottom: spacing.sm, marginTop: spacing.lg },
    input: {
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: borderRadius.md,
        padding: spacing.lg,
        fontSize: fontSize.lg,
        fontFamily: fontFamily.regular,
        color: colors.text,
    },
    amountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: borderRadius.md,
        paddingLeft: spacing.lg,
    },
    currencySymbol: { fontSize: fontSize.xl, fontFamily: fontFamily.semibold, color: colors.primary, marginRight: spacing.sm },
    amountInput: { flex: 1, padding: spacing.lg, fontSize: fontSize.xl, fontFamily: fontFamily.semibold, color: colors.text },
    frequencyRow: { flexDirection: 'row', gap: spacing.sm },
    freqButton: {
        flex: 1,
        paddingVertical: spacing.md,
        borderRadius: borderRadius.md,
        borderWidth: 1,
        borderColor: colors.border,
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    freqButtonActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    freqText: { fontSize: fontSize.sm, fontFamily: fontFamily.semibold, color: colors.textLight },
    freqTextActive: { color: colors.textWhite },
    categoriesScroll: { marginBottom: spacing.md },
    catChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.md,
        borderRadius: borderRadius.xl,
        borderWidth: 1,
        borderColor: colors.border,
        marginRight: spacing.sm,
        backgroundColor: colors.background,
    },
    catChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    catText: { fontSize: fontSize.sm, fontFamily: fontFamily.regular, color: colors.textLight, marginLeft: spacing.xs },
    catTextActive: { color: colors.textWhite },
    saveButton: {
        backgroundColor: colors.primary,
        padding: spacing.lg,
        borderRadius: borderRadius.lg,
        alignItems: 'center',
        marginTop: spacing.xl,
        ...shadows.colored,
    },
    saveButtonText: { color: colors.textWhite, fontSize: fontSize.lg, fontFamily: fontFamily.bold },
    recurringSection: {
        marginHorizontal: spacing.xl,
        marginTop: spacing.lg,
        marginBottom: spacing.sm,
        backgroundColor: colors.surface,
        borderRadius: borderRadius.lg,
        padding: spacing.lg,
        borderWidth: 1,
        borderColor: colors.primary + '25',
    },
    recurringSectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
        marginBottom: spacing.xs,
    },
    recurringSectionTitle: {
        fontSize: fontSize.base,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    recurringSectionHint: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
        marginBottom: spacing.md,
    },
    detectButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing.sm,
        backgroundColor: colors.primary,
        borderRadius: borderRadius.full,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.lg,
    },
    detectButtonDisabled: { opacity: 0.6 },
    detectButtonText: {
        color: colors.textWhite,
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
    },
    suggestionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: spacing.md,
        backgroundColor: colors.background,
        borderRadius: borderRadius.md,
        padding: spacing.md,
        borderWidth: 1,
        borderColor: colors.border,
    },
    suggestionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
        flex: 1,
    },
    suggestionInfo: { flex: 1 },
    suggestionDesc: {
        fontSize: fontSize.sm,
        fontFamily: fontFamily.semibold,
        color: colors.text,
    },
    suggestionMeta: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
        marginTop: 2,
    },
    convertButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: spacing.sm,
    },
    noSuggestionsText: {
        fontSize: fontSize.xs,
        fontFamily: fontFamily.regular,
        color: colors.textLight,
        textAlign: 'center',
        marginTop: spacing.md,
    },
});
